### ISSUE TITLE
HC-05 modülü ve iPhone

### ISSUE THREAD

**Issue by rereprep** [cogullu/RPPicoDS#1]
Merhaba,
HC-05 modülü bluetooth 2.0 olması sebebiyle ne yazık ki iPhone'lar ile çalışmıyor, bu sebeple sadece android telefonlar ile kullanılabiliyor.  Bunla ilgili bir alternatif çözümünüz olabilir mi? (başka modül kullanımı gibi)

**Comment by cogullu** [comment]
Deney seti için soruyorsanız, üzerinde SMD HC05 modülü kullanıldı, bu yüzden başka modül kullanmak imkansız.

**Comment by rereprep** [comment]
Bilgilendirme için çok teşekkür ederim.
