### ISSUE TITLE
RGB LED Pin Farklılığı

### ISSUE THREAD

**Issue by rereprep** [cogullu/RPPicoDS#2]
Bendeki Raspberry Pi Pico İçin Deney Setinde RGB LED için Pin 16 Mavi, Pin 17 Yeşil ve Pin 18 Kırmızıyı gösteriyor. Örnek 10 ve Örnek 11'de ise Pin 16 Mavi, Pin 17 Kırmızı, Pin 18 Yeşil olarak kullanılmış. Yani Mavi Pin kodu aynıyken, Yeşil ve Kırmızı pinler yer değiştirmiş. Hata kodda mı yoksa beni aldığım set mi farklı lehimlenmiş emin olamadığım için yazıyorum. Video, kod örneği vs. gönderebilirim.

**Comment by cogullu** [comment]
Merhaba, tesbitiniz için teşekkürler. 
Tasarım aşamasında 16 mavi, 17 yeşil ve 18 kırmızı için düşünülmüştü. PCB aşamasında yeşil ve kırmızının yerleri değişti. Yani kodda hata vardır, koddaki pinlerin yerlerini değiştirin lütfen.

**Comment by cogullu** [comment]
Kodlardaki hata düzeltildi.

**Comment by rereprep** [comment]
Bilgilendirme için çok teşekkür ederim.
